### ISSUE TITLE
Missing elements?

### ISSUE THREAD

**Issue by DoubleAPowerBox** [tulXoro/Data_Structure_Visualizations#5]
After using list.add(index, data), using list.add(data) doesn't add the element to the list.

**Comment by DoubleAPowerBox** [comment]
![image](https://user-images.githubusercontent.com/55107564/104252177-359e7680-5426-11eb-8114-bd816ddc1243.png)

**Comment by DoubleAPowerBox** [comment]
![image](https://user-images.githubusercontent.com/55107564/104252224-5d8dda00-5426-11eb-8995-dc88225964ef.png)
Adding in a new element makes the previously missing one appear.

**Comment by tulXoro** [comment]
Fixed the issue. It was probably a problem related to the add method not correctly changing the internal size of the linked list.
